#!/bin/bash
# 🚀 Quick Deploy Script - Run these commands step by step

echo "========================================="
echo "🔧 FLUENTIA DEPLOYMENT GUIDE"
echo "========================================="
echo ""

echo "Step 1: Test Authentication Fix (LOCAL)"
echo "----------------------------------------"
echo "1. Open browser DevTools (F12)"
echo "2. Console: localStorage.clear()"
echo "3. Try login with WRONG password → Should FAIL ❌"
echo "4. Try login with CORRECT password → Should work ✅"
echo ""
read -p "✓ Tested locally? (y/n): " tested
echo ""

echo "Step 2: Commit & Push Changes"
echo "----------------------------------------"
read -p "Ready to commit? (y/n): " ready
if [ "$ready" = "y" ]; then
    git add .
    git commit -m "Fix auth bug and prepare for deployment"
    git push origin main
    echo "✅ Pushed to GitHub!"
fi
echo ""

echo "Step 3: Deploy Backend to Render"
echo "----------------------------------------"
echo "1. Go to: https://render.com"
echo "2. Sign up with GitHub"
echo "3. New + → Web Service"
echo "4. Connect repo: Abhishekjc19/fluentia"
echo "5. Settings:"
echo "   - Name: fluentia-backend"
echo "   - Root Directory: backend"
echo "   - Build: npm install && npm run build"
echo "   - Start: npm start"
echo "   - Plan: Free"
echo ""
echo "6. Environment Variables (IMPORTANT):"
echo "   Copy from: .env.production.example"
echo "   Especially:"
echo "   - SUPABASE_URL"
echo "   - SUPABASE_SERVICE_KEY"
echo "   - JWT_SECRET"
echo "   - GEMINI_API_KEY"
echo ""
read -p "✓ Backend deployed? Enter your Render URL: " backend_url
echo ""

echo "Step 4: Deploy Frontend to Vercel"
echo "----------------------------------------"
echo "1. Go to: https://vercel.com"
echo "2. Sign up with GitHub"
echo "3. Add New... → Project"
echo "4. Import: Abhishekjc19/fluentia"
echo "5. Settings:"
echo "   - Framework: Vite"
echo "   - Root Directory: frontend"
echo ""
echo "6. Environment Variables:"
echo "   VITE_API_URL=$backend_url/api"
echo "   VITE_GOOGLE_CLIENT_ID=<your_google_client_id>"
echo ""
read -p "✓ Frontend deployed? Enter your Vercel URL: " frontend_url
echo ""

echo "Step 5: Update Backend CORS"
echo "----------------------------------------"
echo "1. Go to Render → fluentia-backend → Environment"
echo "2. Add/Update:"
echo "   CORS_ORIGIN=$frontend_url"
echo "3. Service will auto-redeploy"
echo ""
read -p "✓ CORS updated? (y/n): " cors
echo ""

echo "Step 6: Update Google OAuth"
echo "----------------------------------------"
echo "1. Go to: https://console.cloud.google.com"
echo "2. APIs & Services → Credentials"
echo "3. Edit OAuth 2.0 Client"
echo "4. Add Authorized JavaScript origins:"
echo "   $frontend_url"
echo "5. Add Authorized redirect URIs:"
echo "   $frontend_url/dashboard"
echo ""
read -p "✓ Google OAuth updated? (y/n): " oauth
echo ""

echo "========================================="
echo "🎉 DEPLOYMENT COMPLETE!"
echo "========================================="
echo ""
echo "Your app is live at:"
echo "  Frontend: $frontend_url"
echo "  Backend:  $backend_url"
echo ""
echo "Next steps:"
echo "1. Visit $frontend_url"
echo "2. Test signup/login"
echo "3. Try WRONG password (should fail!)"
echo "4. Test interview features"
echo ""
echo "📚 See detailed guides:"
echo "  - DEPLOYMENT-CHECKLIST.md"
echo "  - DEPLOY-RENDER.md"
echo "  - DEPLOY-VERCEL.md"
echo ""
echo "Happy deploying! 🚀"
